---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: local
    hooks:
        - id: git-secrets
          name: git-secrets
          entry: git-secrets
          language: system
          args: ["--scan"]
