---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  snyk: snyk/snyk@0.0.10

# yaml anchor filters
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/


workflows:
  benchmark-docker-image-pipeline:
    jobs:
      - docker/hadolint:
          filters: *on-push-master
      - docker/publish:
          name: test-build
          context: ci
          deploy: false
          image: feedyard/docker-benchmark
          lint-dockerfile: true
          requires:
            - docker/hadolint
          filters: *on-push-master
          after_build:
            - snyk/scan:
                docker-image-name: 'feedyard/docker-benchmark:$CIRCLE_SHA1'
                organization: feedyard
                fail-on-issues: false
                monitor-on-build: false
            - run:
                command: |
                  CID=$(docker run --name cis-test-docker-benchmark \
                                   -it -d --entrypoint "/bin/ash" \
                                   "feedyard/docker-benchmark:$CIRCLE_SHA1")
                  docker run -it \
                             -v /var/run/docker.sock:/var/run/docker.sock \
                             -e CONTAINER_NAME="feedyard/docker-benchmark" \
                             -e CONTAINER_TAG="$CIRCLE_SHA1" \
                             -e CID="$CID" \
                             "feedyard/docker-benchmark:0.1.4" standard
      - docker/publish:
          name: release
          context: ci
          image: feedyard/docker-benchmark
          tag: '$CIRCLE_TAG,latest'
          filters: *on-tag-master
