---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  snyk: snyk/snyk@0.0.10

# yaml anchor filters
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/


workflows:
  benchmark-docker-image-pipeline:
    jobs:
      - docker/hadolint:
          filters: *on-push-master
      - docker/publish:
          context: ci
          deploy: false
          image: feedyard/docker-benchmark
          lint-dockerfile: true
          requires:
            - docker/hadolint
          filters: *on-push-master
          after_build:
            - snyk/scan:
                docker-image-name: 'feedyard/docker-benchmark:$CIRCLE_SHA1'
                organization: feedyard
                fail-on-issues: false
                monitor-on-build: false
      - docker/publish:
          context: ci
          image: feedyard/docker-benchmark
          tag: '$CIRCLE_TAG,latest'
          filters: *on-tag-master

