---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  snyk: snyk/snyk@0.0.10

# yaml anchor filters
dev-build-filter: &dev-build-filter
  branches:
    only: /master/
  tags:
    ignore: /.*/

tag-publish-filter: &tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /.*/


workflows:
  benchmark-docker-image-pipeline:
    jobs:
      - docker/hadolint:
          filters: *dev-build-filter
      # - docker/publish:
      #     deploy: false
      #     image: feedyard/docker-benchmark
      #     lint-dockerfile: true
      #     requires:
      #       - docker/hadolint
      #     # after_build:
      #     #   - snyk/scan:
      #     #       docker-image-name: 'feedyard/docker-benchmark:$CIRCLE_SHA1'
      #     #       organization: feedyard
      #     #       fail-on-issues: false
      #     filters: *dev-build-filter
      # - docker/publish:
      #     image: feedyard/docker-benchmark
      #     tag: $CIRCLE_TAG
      #     context: ci
      #     after_build:
      #       - run:
      #           command: 
      #     filters: *tag-publish-filter
